### ISSUE TITLE
Define a naming convention for buttons, labels, widgets, and other Qt UI Objects

### ISSUE THREAD

**Issue by EDKarlsson** [home-run/subtle-cosmic-moose#18]

**Comment by ozyx** [comment]
i propose firstly, ALL LOWERCASE.
secondly, have names be like this - <parent_object>-<object type>-<more specific identifier if needed>

so like,

mainwindow_pushbutton_plantrip

**Comment by EDKarlsson** [comment]
So the syntax style would be : 

containerobject_widgetobject_purpose

ie: window_action_purpose

eg: 
1) mainwindow_pushbutton_plantrip

2) loginwindow_pushbutton_login

3) loginwindow_label_username

**Comment by ozyx** [comment]
yea exactly!
makes it easy to find what you're trying to look for

**Comment by ozyx** [comment]
i can add this to the readme

**Comment by EDKarlsson** [comment]
Awesomesauce!

**Comment by Axelm3sh** [comment]
Lol When I proposed this to my previous team members they just rolled with whatever they wanted and ignored me. I had a legit reason to be all smug when they couldn't tell which variables led to what.
Cool beans
