### ISSUE TITLE
Create Application Flow

### ISSUE THREAD

**Issue by EDKarlsson** [home-run/subtle-cosmic-moose#19]
This should be done in tandem with the design of the GUI. 

Drawing the flow of the application for getting to each requirement will help design the application GUI.

Reason this is a separate task from the design GUI is because this is not taking in consideration of placement of buttons, views, etcetera...

**Comment by ozyx** [comment]
right. so this is like our "use cases" from last project which lay out the user experience. I.e:
user starts program -> user is presented with choices -> chooses choice 1-> something happens

amirite

**Comment by EDKarlsson** [comment]
Yea, this time I think we should write these out in advance.

**Comment by ozyx** [comment]
agree. so if we have time in lab today, which we **hopefully do** , we can work on some planning stuff

**Comment by ozyx** [comment]
if we can work on this stuff today I hope by tomorrow people can start pulling tasks and working on stuff
