### ISSUE TITLE
QtTest doesn't run any new unit tests, only initTest().

### ISSUE THREAD

**Issue by ozyx** [home-run/subtle-cosmic-moose#22]
I added a unit test called testOpenDB() or something along those lines. However, no matter how many times I clean and rebuild the project, QtTest seems to only want to run the setup, initTest() and tearDown(). I can change those methods and the test results change, but it won't run any tests that aren't the default ones.
@EDKarlsson Any insight? No rush.

**Comment by EDKarlsson** [comment]
Weird... I'll look into this on the way home from work.

**Comment by ozyx** [comment]
Just check out my branch and run the test you'll be able to see what I'm talking about
