### ISSUE TITLE
Implement Dijkstra's algorithm for finding the shortest path between two stadiums.

### ISSUE THREAD

**Issue by ozyx** [home-run/subtle-cosmic-moose#48]
Depends on #42 
Subtask for #8, #9, #14, #27
**Definition of Done**
1. Dijkstra's algorithm should be implemented for use with a Graph object.
2. Must be able to find the shortest path between two Stadiums on the Graph.
3. Unit tests for total distance and path taken must be written and passing.
4. Code must be fully documented using Doxygen comment blocks.

**Test Scenarios**
1. Verify total distance of a path is accurate.
2. Verify path taken is accurate.
3. Verify that the original Graph is not modified in any way by the algorithm.

**Comment by EDKarlsson** [comment]
I concur doctor, I concur!
