### ISSUE TITLE
As a baseball fan I can plan a trip with the shortest distance starting at Dodger stadium and visiting every other stadium.

### ISSUE THREAD

**Issue by ozyx** [home-run/subtle-cosmic-moose#9]
Blockers:  #48 #42
**Definition of Done**
- Calculation is done using Djiksta's algorithm
- Trip starts at Dodger stadium and visits every other stadium.

**Test Scenarios**
- Verify answer is correct
- Verify calculated trip distance
- Verify all other stadiums have been visited in addition to Dodgers stadium

**Comment by EDKarlsson** [comment]
Why was this reopened? This one works, it's the 'custom' trip feature that needs to be fixed."

**Comment by ozyx** [comment]
Closing.
